/*************************************************************
 * BatSpy: Teensy 4.1 based recording device for bat sounds  *
 * ***********************************************************
 * Copyright (C) 2021 Christian Mueller                      *
 *                    chrmue44(AT)gmail{DOT}com              *
 * License: GNU GPLv3.0                                      *
 * ***********************************************************/

#include <Arduino.h>
#include "config.h"
#include "ctext.h"


tText TGE_NOT_FOUND[] = "Textnummer unbekannt:";
tText TGE_ASC_0[] = "          01234567 89ABCDEF 01234567 89ABCDEF";
tText TGE_ASC_1[] = "00 .. 1F: \x20\x01\x02\x03\x04\x05\x06\x07 \x08\x09\x20\x0B\x0C\x20\x0E\x0F \x10\x11\x12\x13\x14\x15\x16\x17 \x18\x19\x1A\x1B\x1C\x1D\x1E\x1F";
tText TGE_ASC_2[] = "20 .. 3F: \x20\x21\x22\x23\x24\x25\x26\x27 \x28\x29\x2A\x2B\x2C\x2D\x2E\x2F \x30\x31\x32\x33\x34\x35\x36\x37 \x38\x39\x3A\x3B\x3C\x3D\x3E\x3F";
tText TGE_ASC_3[] = "40 .. 5F: \x40\x41\x42\x43\x44\x45\x46\x47 \x48\x49\x4A\x4B\x4C\x4D\x4E\x4F \x50\x51\x52\x53\x54\x55\x56\x57 \x58\x59\x5A\x5B\x5C\x5D\x5E\x5F";
tText TGE_ASC_4[] = "60 .. 7F: \x60\x61\x62\x63\x64\x65\x66\x67 \x68\x69\x6A\x6B\x6C\x6D\x6E\x6F \x70\x71\x72\x73\x74\x75\x76\x77 \x78\x79\x7A\x7B\x7C\x7D\x7E\x7F";
tText TGE_ASC_5[] = "80 .. 9F: \x80\x81\x82\x83\x84\x85\x86\x87 \x88\x89\x8A\x8B\x8C\x8D\x8E\x8F \x90\x91\x92\x93\x94\x95\x96\x97 \x98\x99\x9A\x9B\x9C\x9D\x9E\x9F";
tText TGE_ASC_6[] = "A0 .. BF: \xA0\xA1\xA2\xA3\xA4\xA5\xA6\xA7 \xA8\xA9\xAA\xAB\xAC\xAD\xAE\xAF \xB0\xB1\xB2\xB3\xB4\xB5\xB6\xB7 \xB8\xB9\xBA\xBB\xBC\xBD\xBE\xBF";
tText TGE_ASC_7[] = "C0 .. DF: \xC0\xC1\xC2\xC3\xC4\xC5\xC6\xC7 \xC8\xC9\xCA\xCB\xCC\xCD\xCE\xCF \xD0\xD1\xD2\xD3\xD4\xD5\xD6\xD7 \xD8\xD9\xDA\xDB\xDC\xDD\xDE\xDF";
tText TGE_ASC_8[] = "E0 .. FF: \xE0\xE1\xE2\xE3\xE4\xE5\xE6\xE7 \xE8\xE9\xEA\xEB\xEC\xED\xEE\xEF \xF0\xF1\xF2\xF3\xF4\xF5\xF6\xF7 \xF8\xF9\xFA\xFB\xFC\xFD\xFE\xFF";
tText TGE_DOUBLE[] = "Doppelte Schriftgröße";

struct stTxtList PROGMEM Texts[] =
{
  {     0, ""                          ,""},
  {     1, "Anzeige"                   ,"Display"},
  {     2, "Start/Stopp"               ,"Start/Stop"},
  {     3, ""                          ,""},
  {     4, "Einstellung"               ,"Setup"},
  {     5, "Formatieren..."            ,"Format..."},
  {     6, "GPX Ein/Aus"               ,"GPX On/Off"},
  {    10, "OK"                        ,0},
  {    11, "Information"               ,"Info"},
  {    15, "Ja"                        ,"Yes"},
  {    16, "Nein"                      ,"No"},
  {    20, "Hören direkt"              ,"Hear direct"},
  {    21, "Hören HET"                 ,"Hear HET"},
  {    22, "Abspielen direkt"          ,"Play direct"},
  {    23, "Abspielen gedehnt (10x)"   ,"Play stretched 10x"},
  {    24, "Abspielen HET"             ,"Play HET"},
  {    25, "Automatische Aufnahme"     ,"Auto Recording"},
  {    30, "Status"                    ,0},
  {    32, "Projekt-Notizen 1"         ,"Project Notes 1"},
  {    33, "Projekt-Notizen 2"         ,"Project Notes 2"},
  {   100, "Übersicht"                 ,"Overview"},
  {   101, "Live-Anzeige"              ,"Live display"},
  {   102, "Datei-Manager"             ,"File Manager"},
  {   103, "Zeitdiagramm"              ,"Xt diagram"},
  {   104, "Wasserfall"                ,"Water fall diagram"},
  {   105, "Information"               ,0},
  {   106, "Bat-Info"                  ,"Bat-Info"  },
  {   107, "Font-Tabelle"              ,"Font Table"},
  {   108, "Ausschalten"               ,"Power Off"},
  {   150, "Übersicht"                 ,"Overview"},
  {   190, "Anzahl Satelliten"         ,"Number of Satellites"},
  {   191, "GPS Log an"                ,"GPS Log on"},
  {   193, "Höhe [m]"                  ,"Height [m]"},
  {   195, "Position gültig"           ,"Position valid"},
  {   200, "GPS Position"              ,0},
  {   201, "Zeit"                      ,"Time"},
  {   202, "Betriebsart"               ,"Operation mode"},
  {   203, "Mischfrequenz [kHz]"       ,"Mixer freq [kHz]"},
  {   204, "Lautstärke"                ,"Volume"},
  {   205, "Datei"                     ,"File"},
  {   206, "Verzeichnis"               ,"Directory"},
  {   208, "Name"                      ,0},
  {   210, "Empfindlichkeit"           ,"Sensitivity"},
  {   220, "Datei-Filter"              ,"File Filter"},
  {   221, "*.*"                       ,0},
  {   222, "*.wav"                     ,0},
  {   223, "*.raw"                     ,0},
  {   224, "*.xml"                     ,0},
  {   225, "*.log"                     ,0},
  {   230, "   \x1e"                   ,0},
  {   235, "   \x1f"                   ,0},
  {   300, "kHz"                       ,0},
  {   301, "s"                         ,0},
  {   302, "%"                         ,0},
  {   305, "[s/div]"                   ,0},
  {   306, "Pegel"                     ,"Level"},
  {   307, "%"                         ,0},
  {   308, "Mess."                     ,"Meas."},
  {   309, "Init CPU max."             ,0},
  {   310, "vorige"                    ,"previous"},
  {   311, "nächste"                   ,"next"},
  {   320, "gestoppt"                  ,"stopped"},
  {   325, "Abspielen läuft"           ,"Playing"},
  {   335, "Aufnahme läuft"            ,"Recording"},
  {   337, "Sperrzeit"                 ,"Timeout" },
  {   400, "CPU audio avg"             ,0},
  {   401, "%"                         ,0},
  {   405, "CPU audio max"             ,0},
  {   410, "MEM blocks audio"          ,0},
  {   415, "Spitzenwert"               ,"Peak Value"},
  {   430, "Software-Version"          ,"Software Version"},
  {   435, "Hardware-Version"          ,"Hardware Version"},
  {   440, "Freier Speicher [MB]"      ,"Free Disk Space [MB]"},
  {   450, "Versorgungsspannung [V]"   ,"Supply Voltage [V]"},
  {   455, "Temperatur [°C]"           ,"Temperature [°C]"},
  {   470, "Ablenkgeschw."             ,"Sweep Speed"},
  {   475, "Amplitude"                 ,"Amplitude"},
  {   480, "ms/div"                    ,0},
  {   500, "Sel."                      ,0},
  {   510, "Entf."                     ,"Del."},

  {  1000, "Über..."                   ,"About..."},
  {  1001, "Laden ..."                 ,"Load ..."},
  {  1005, "Sollen die Parametereinstellungen"," "},
  {  1006, "geladen werden?"           ,"Load settings?"},
  {  1010, "Wollen Sie wirklich ausschalten?", "Do you really want to power off?"},
  {  1015, "Manueller Start nur möglich","Manual start only possible for"},
  {  1016, "für Projektformat Datum/Uhrzeit","project format date/time"},
  {  1021, "Speichern ..."             ,"Save ..."},
  {  1025, "gespeichert werden?"       ,"Save settings?"},
  {  1030, "Parameter allgemein"       ,"Parameter misc."},
  {  1031, "Datum/Uhrzeit"             ,"Time/Date"},
  {  1032, "Stellen"                   ,"Set"},
  {  1033, "Position"                  ,0},
  {  1034, "Parameter Aufnahme"        ,"Parameter Recording"},
  {  1040, "Soll die SD-Karte wirklich formatiert werden?", "Do you really want to format the SD card?"},
  { 1041, "Alle Daten werden gelöscht!", "All data will be lost!" },
  { 1042, "FEHLER: Formatierung fehlgeschlagen", "ERROR: foramting failed" },
  { 1043, "Formatierung abgeschlossen","Formating completed" },
  { 1100, "Anzeigesprache"            ,"Language" },
  { 1101, "Deutsch"                   ,0 },
  { 1102, "English"                   ,0 },
  { 1110, "Abtastrate [ks/s]"         ,"Sampling rate [ks/s]" },
  { 1120, "Aufnahmedauer [s]"         ,"Recording time [s]" },
  { 1130, "10x"                       ,0 },
  { 1131, "20x"                       ,0 },
  { 1140, "Schwellwert Aufnahme [db]" ,"Threshhold recording [dB]" },
  { 1142, "Datum"                     ,"Date" },
  { 1143, "Zeit"                      ,"Time" },
  { 1144, "Totzeit n. Aufnahme [s]"   ,"Timeout after rec. [s]" },
  { 1145, "Dateiformat"               ,"File format" },
  { 1146, "RAW"                       , 0 },
  { 1147, "WAV"                       , 0 },
  { 1148, "Nachleuchtzeit [s]"        ,"Backlight time [s]" },
  { 1150, "Drehsinn Drehknopf"        ,"Direction rotary knob" },
  { 1151, "Uhrzeigersinn"             ,"Clockwise" },
  { 1152, "Gegenuhrzeigersinn"        ,"Counter clockwise" },
  { 1160, "Anzeige:"                  ,"Display:" },
  { 1161, "Linkshänder"               ,"left handed" },
  { 1162, "Rechtshänder"              ,"right handed" },
  { 1165, "Kal. Spannung [V]"         ,"Cal. Voltage [V]" },
  { 1167, "Verzögerung Tx USB [ms]"   ," Delay Tx USB [ms]" },
  { 1170, "Trig. Filter [kHz]"        ,0 },
  { 1171, "Hochpass"                  ,"High pass" },
  { 1172, "Tiefpass"                  ,"Low pass" },
  { 1173, "Bandpass"                  ,"Band pass" },
  { 1175, "Filtertyp"                 ,"Filter type" },
  { 1180, "Startzeit Aufnahme"        ,"Start Time Recording" },
  { 1181, "Stoppzeit Aufnahme"        ,"Stop Time Recording" },
  { 1182, ":"                         ,0 },
  { 1190, "Projektformat"             ,"Project format" },
  { 1191, "Tag/Uhrzeit"               ,"Date/Time" },
  { 1192, "Elekon"                    ,0 },
  { 1200, "Name deutsch"              ,"Name" },
  { 1202, "Name latein"               ,"Name lat." },
  { 1204, "Hauptfreq. [kHz]"          ,"Main freq. [kHz]" },
  { 1206, "min."                      ,"min." },
  { 1208, "max."                      ,"max." },
  { 1210, "Ruflänge [ms]"             ,"Call length [ms]" },
  { 1212, "Rufabstand [ms]"           ,"Call dist. [ms]" },
  { 1215, "Charakteristik"            ,"Characterictic" },
  { 1217, "Vorkommen"                 ,"Ocurrence" },
  { 1220, "Spannweite [mm]"           ,"Wing Span [mm]" },
  { 1225, "Gewicht [g]"               ,"Weight [g]" },
  { 1230, "Lebensraum"                ,"Habitat" },
  { 1235, "Bemerkungen"               ,"Comments" },
  { 1300, "17.6"                      ,0 },
  { 1301, "19.2"                      ,0 },
  { 1302, "23.4"                      ,0 },
  { 1303, "28.1"                      ,0 },
  { 1304, "32"                        ,0 },
  { 1305, "35.3"                      ,0 },
  { 1306, "38.4"                      ,0 },
  { 1307, "44.1"                      ,0 },
  { 1308, "48"                        ,0 },
  { 1309, "88"                        ,0 },
  { 1310, "96"                        ,0 },
  { 1311, "176"                       ,0 },
  { 1312, "192"                       ,0 },
  { 1313, "234"                       ,0 },
  { 1314, "281"                       ,0 },
  { 1315, "312"                       ,0 },
  { 1316, "352"                       ,0 },
  { 1317, "384"                       ,0 },
  { 1318, "480"                       ,0 },

  { 1320, "Filter",                    0 },
  { 1321, "aus",                       "off" },
  { 1322, "HP 16kHz",                  0 },

  { 1325, "Verstärkung",               "Gain" },
  { 1330, "Pre Trigger [ms]",          0 },
  { 1331, "27 dB",                     0 },
  { 1332, "36 dB",                     0 },
  { 1333, "45 dB",                     0 },
  { 1334, "54 dB",                     0 },

  { 1338, "letzter Ruf [kHz]",         "last call [kHz]" },

  { 1340, "°",                         0 },
  { 1341, "N",                         0 },
  { 1342, "S",                         0 },
  { 1343, "E",                         0 },
  { 1344, "W",                         0 },
  { 1345, ".",                         0 },
  { 1350, "30 dB",                     0 },
  { 1351, "33 dB",                     0 },
  { 1352, "40 dB",                     0 },
  { 1353, "48 dB",                     0 },
  { 1354, "53 dB",                     0 },
  { 1355, "58 dB",                     0 },
  { 1360, "Trigger",                   "Trigger" },
  { 1361, "Pegelüberschreitung",       "Exceed Level" },
  { 1362, "Frequenz",                  "Frequency" },
  { 1363, "Frequenz + Pegel",          "Frequency + Level" },
  { 1370, "min. Dauer [ms]",           "min. period [ms]" },
  { 1400, "Aus",                       "Off"},
  { 1401, "Ein",                       "On"},
  { 1402, "Zeitgesteuert",             "Time controlled"},
  { 1403, "Dämmerung",                 "Twilight"},
  { 1410, "Festwert",                  "fixed value"},
  { 1412, "GPS",                       0},
  { 1420, "Quelle Positionsangabe",    "Source position indication"},
  { 1500, "Fledermausart",             "Bat Species"},
  { 1510, "Parameter einstellen",      "Setup Parameters"},
  { 1600, "Datei wirklich löschen?:",  "Really delete file?:"},
  { 1700, "Open Source Fledermausdetektor", "Open Source bat recording and detection device"},
  { 1702, "Software Version: "         ,0 },
  { 1704, "Taste drücken, um fortzufahren", "press button to continue!"},
  { 1710, "Dialoge",                   "Dialogs"},
  { 1711, "Experte",                   "Expert"},
  { 1712, "Recorder",                  "Recorder"},
  { 1713, "Handgerät",                 "Handheld" },
  { 2000, "offene Landschaft",         "open land"},
  { 2001, "einzelne Bäume & Häuser",   "single trees & houses"},
  { 2002, "Straße",                    "street"},
  { 2003, "Waldweg",                   "forest track" },
  { 2004, "dichter Wald",              "forest" },
  { 2005, "Waldweiher",                "pond surrounded by forrest" },
  { 2010, "klarer Himmel",             "blue sky" },
  { 2011, "bewölkt trocken",           "cloudy no rain" },
  { 2012, "bewölkt Schauer",           "cloudy with rainshowers" },
  { 2013, "Regen",                     "rain" },

  { 12000, TGE_ASC_0           ,0},
  { 12001, TGE_ASC_1           ,0},
  { 12002, TGE_ASC_2           ,0},
  { 12003, TGE_ASC_3           ,0},
  { 12004, TGE_ASC_4           ,0},
  { 12005, TGE_ASC_5           ,0},
  { 12006, TGE_ASC_6           ,0},
  { 12007, TGE_ASC_7           ,0},
  { 12008, TGE_ASC_8           ,0},
  { 12010, TGE_DOUBLE          ,0},
  { 0xFFFF   , "",""},
};
