/*************************************************************
 * BatSpy: Teensy 4.1 based recording device for bat sounds  *
 * ***********************************************************
 * Copyright (C) 2021 Christian Mueller                      *
 *                    chrmue44(AT)gmail{DOT}com              *
 * License: GNU GPLv3.0                                      *
 * ***********************************************************/

#include <Arduino.h>
#include "config.h"
#include "ctext.h"


tText TGE_NOT_FOUND[] = "Textnummer unbekannt:";
tText TGE_ASC_0[] = ")         01234567 89ABCDEF 01234567 89ABCDEF";
tText TGE_ASC_1[] = "00 .. 1F: \x20\x01\x02\x03\x04\x05\x06\x07 \x08\x09\x20\x0B\x0C\x20\x0E\x0F \x10\x11\x12\x13\x14\x15\x16\x17 \x18\x19\x1A\x1B\x1C\x1D\x1E\x1F";
tText TGE_ASC_2[] = "20 .. 3F: \x20\x21\x22\x23\x24\x25\x26\x27 \x28\x29\x2A\x2B\x2C\x2D\x2E\x2F \x30\x31\x32\x33\x34\x35\x36\x37 \x38\x39\x3A\x3B\x3C\x3D\x3E\x3F";
tText TGE_ASC_3[] = "40 .. 5F: \x40\x41\x42\x43\x44\x45\x46\x47 \x48\x49\x4A\x4B\x4C\x4D\x4E\x4F \x50\x51\x52\x53\x54\x55\x56\x57 \x58\x59\x5A\x5B\x5C\x5D\x5E\x5F";
tText TGE_ASC_4[] = "60 .. 7F: \x60\x61\x62\x63\x64\x65\x66\x67 \x68\x69\x6A\x6B\x6C\x6D\x6E\x6F \x70\x71\x72\x73\x74\x75\x76\x77 \x78\x79\x7A\x7B\x7C\x7D\x7E\x7F";
tText TGE_ASC_5[] = "80 .. 9F: \x80\x81\x82\x83\x84\x85\x86\x87 \x88\x89\x8A\x8B\x8C\x8D\x8E\x8F \x90\x91\x92\x93\x94\x95\x96\x97 \x98\x99\x9A\x9B\x9C\x9D\x9E\x9F";
tText TGE_ASC_6[] = "A0 .. BF: \xA0\xA1\xA2\xA3\xA4\xA5\xA6\xA7 \xA8\xA9\xAA\xAB\xAC\xAD\xAE\xAF \xB0\xB1\xB2\xB3\xB4\xB5\xB6\xB7 \xB8\xB9\xBA\xBB\xBC\xBD\xBE\xBF";
tText TGE_ASC_7[] = "C0 .. DF: \xC0\xC1\xC2\xC3\xC4\xC5\xC6\xC7 \xC8\xC9\xCA\xCB\xCC\xCD\xCE\xCF \xD0\xD1\xD2\xD3\xD4\xD5\xD6\xD7 \xD8\xD9\xDA\xDB\xDC\xDD\xDE\xDF";
tText TGE_ASC_8[] = "E0 .. FF: \xE0\xE1\xE2\xE3\xE4\xE5\xE6\xE7 \xE8\xE9\xEA\xEB\xEC\xED\xEE\xEF \xF0\xF1\xF2\xF3\xF4\xF5\xF6\xF7 \xF8\xF9\xFA\xFB\xFC\xFD\xFE\xFF";
tText TGE_DOUBLE[] = "Doppelte Schriftgröße";

extern const struct stTxtList PROGMEM Texts[] =
{
  {     0, F("")                         ,F("")},
  {     1, F("Anzeige")                   ,F("Display")},
  {     2, F("Start/Stopp")              ,F("Start/Stop")},
  {     3, F("")                         ,F("")},
  {     4, F("Einstellung")              ,F("Setup")},
  {     5, F("Format...")                ,F("Format...")},
  {     6, F("GPX Ein/Aus")              ,F("GPX On/Off")},
  {     7, F("Seite")                    ,F("Page")},
  {     8, F("St/St")                    , 0},
  {    10, F("OK")                       ,0},
  {    11, F("Information")              ,F("Info")},
  {    15, F("Ja")                       ,F("Yes")},
  {    16, F("Nein")                     ,F("No")},
  {    20, F("Hören direkt")             ,F("Hear direct")},
  {    21, F("Hören HET")                ,F("Hear HET")},
  {    22, F("Abspielen direkt")         ,F("Play direct")},
  {    23, F("Abspielen gedehnt (10x)")  ,F("Play stretched 10x")},
  {    24, F("Abspielen HET")            ,F("Play HET")},
  {    25, F("Automatische Aufnahme")    ,F("Auto Recording")},
  {    26, F("Aufnahme")                 ,F("Record")},
  {    27, F("Aufnahmen")                ,F("Recordings")},
  {    28, F("Aufnahme")                 ,F("Recording")},
  {    30, F("GPS Status")               ,0},
  {    32, F("Projekt-Notizen 1")        ,F("Project Notes 1")},
  {    33, F("Projekt-Notizen 2")        ,F("Project Notes 2")},
  {   100, F("Hauptseite")               ,F("Main Page")},
  {   101, F("Live-Anzeige")             ,F("Live display")},
  {   102, F("Datei-Manager")            ,F("File Manager")},
  {   103, F("Zeitdiagramm")             ,F("Xt diagram")},
  {   104, F("Wasserfall")               ,F("Water fall diagram")},
  {   105, F("Information")              ,0},
  {   106, F("Bat-Info")                 ,F("Bat-Info") },
  {   107, F("Font-Tabelle")             ,F("Font Table")},
  {   108, F("Ausschalten...")           ,F("Power Off...")},
  {   110, F("Fled.")                    ,F("Bat")},
  {   112, F("Vög.")                     ,F("Bird")},
  {   113, F("SD voll")                  ,F("SD full")},
  {   130, F("Mic Id")                   ,0},
  {   131, F("Mic Typ")                  ,F("Mic Type")},
  // {   150, F("Übersicht")                ,F("Overview")},
  {   190, F("Anzahl Satelliten")        ,F("Number of Satellites")},
  {   191, F("GPS Log an")               ,F("GPS Log on")},
  {   192, F("Sat:")                     ,0 },
  {   193, F("Höhe [m]")                 ,F("Altitute [m]")},
  {   195, F("Position gültig")          ,F("Position valid")},
  {   200, F("GPS Position")             ,0},
  {   201, F("Zeit")                     ,F("Time")},
  {   202, F("Betriebsart")              ,F("Operation mode")},
  {   203, F("Mischfrequenz [kHz]")      ,F("Mixer freq [kHz]")},
  {   204, F("Lautstärke")               ,F("Volume")},
  {   205, F("Datei")                    ,F("File")},
  {   206, F("Verzeichnis")              ,F("Directory")},
  {   208, F("Name")                     ,0},
  {   210, F("Empfindlichkeit")          ,F("Sensitivity")},
  {   220, F("Datei-Filter")             ,F("File Filter")},
  {   221, F("*.*")                      ,0},
  {   222, F("*.wav")                    ,0},
  {   223, F("*.raw")                    ,0},
  {   224, F("*.xml")                    ,0},
  {   225, F("*.log")                    ,0},
  {   230, F(")  \x1e")                  ,0},
  {   235, F(")  \x1f")                  ,0},
  {   300, F("kHz")                      ,0},
  {   301, F("s")                        ,0},
  {   302, F("%")                        ,0},
  {   303, F("°C")                       ,0},
  {   305, F("[s/div]")                  ,0},
  {   306, F("Pegel")                    ,F("Level")},
  {   308, F("Mess.")                    ,F("Meas.")},
  {   309, F("Init CPU max.")            ,0},
  {   310, F("vorige")                   ,F("previous")},
  {   311, F("nächste")                  ,F("next")},
  {   320, F("gestoppt")                 ,F("stopped")},
  {   325, F("Abspielen")                ,F("Playing")},
  {   335, F("Aufnahme")                 ,F("Recording")},
  {   337, F("Sperrzeit")                ,F("Timeout")},
  {   400, F("CPU audio avg")            ,0},
  {   401, F("%")                        ,0},
  {   405, F("CPU audio max")            ,0},
  {   410, F("MEM blocks audio")         ,0},
  {   415, F("Aussteuerung")             ,F("Peak Value")},
  {   430, F("Software-Version")         ,F("Software Version")},
  {   435, F("Hardware-Version")         ,F("Hardware Version")},
  {   437, F("Seriennummer")             ,F("Serial number")},
  {   440, F("Freier Speicher [MB]")     ,F("Free Disk Space [MB]")},
//  {   441, F("Speicher")                ,F("Disk")},
  {   441, F("\x7F")                     ,0},
  {   450, F("Versorgungsspannung [V]")  ,F("Supply Voltage [V]")},
 // {   451, F("Batterie")                 ,F("Battery")},
  {   451, F("\xEC\xEE\xEE\xEE\xED\xED\xED\xED\xEF"), 0},
  {   452, F("V")                        ,0},
  {   453, F("%")                        ,0},
  {   454, F("GB frei")                  ,F("GB free")},
  {   455, F("Temperatur")               ,F("Temperature")},
  {   456, F("Luftfeuchte")              ,F("Humidity")},
  // {   470, F("Ablenkgeschw.")            ,F("Sweep Speed")},
  {   460, F("GPS")                      ,0},
  {   461, F("Sat.")                     ,0},
  {   475, F("Amplitude")                ,F("Amplitude")},
  {   480, F("ms/div")                   ,0},
  {   500, F("Sel.")                     ,0},
  {   510, F("Entf.")                    ,F("Del.")},

  {  1000, F("Über...")                  ,F("About...")},
  {  1001, F("Laden ...")                ,F("Load ...")},
  {  1004, F("Sollen die Werkseinstellungen"), F("Load factory settings")},
  {  1005, F("Sollen die Parametereinstellungen"),F("Load parameter settings")},
  {  1006, F("geladen werden?")          ,F("?")},
  {  1007, F("Sollen die")               ,F("Load")},
  { 1008, F("Parameter")                 ,F("Parameters")},
  { 1009, F("Werkseinstellungen")        ,F("Factory Settings")},
  { 1010, F("Wollen Sie wirklich ausschalten?"), F("Do you really want to power off?")},
  { 1011, F("Wollen Sie wirklich")       ,F("Really")},
  { 1012, F("ausschalten ?")             ,F("power off ? ")},
  { 1015, F("Manueller Start nur möglich"),F("Manual start only possible for")},
  { 1016, F("für Projektformat Datum/Uhrzeit"),F("project format date/time")},
  { 1021, F("Speichern ...")            ,F("Save ...")},
  { 1025, F("gespeichert werden?")      ,F("Save settings?")},
  { 1030, F("Allgemein")                ,F("Miscellaneous.")},
  { 1031, F("Datum/Uhrzeit")            ,F("Time/Date")},
  { 1032, F("Stellen")                  ,F("Set")},
  { 1033, F("???")                      ,F("????")},
  { 1034, F("Aufnahme Flederm.")        ,F("Recording Bats")},
  { 1035, F("Werkseinstellung")         ,F("Factory Defaults")},
  { 1036, F("Aufnahme Vögel")           ,F("Recording Birds")},
  { 1037, F("Aufnahme")                 ,F("Recording")},
  { 1040, F("Soll die SD-Karte wirklich formatiert werden?"), F("Do you really want to format the SD card?")},
  { 1041, F("Alle Daten werden gelöscht!"), F("All data will be lost!")},
  { 1042, F("FEHLER: Formatierung fehlgeschlagen"), F("ERROR: foramting failed")},
  { 1043, F("Formatierung abgeschlossen"),F("Formating completed")},
  { 1044, F("SD-Karte")                 ,F("Format SD card?")},
  { 1045, F("formatieren?")             ,F("")},
  { 1046, F("Alle Daten")               ,F("All data will")},
  { 1047, F("werden gelöscht!")         ,F("be deleted!")},
  { 1100, F("Sprache")                  ,F("Language")},
  { 1101, F("Deutsch")                  ,0 },
  { 1102, F("English")                  ,0 },
  { 1110, F("Abtastrate [ks/s]")        ,F("Sampling rate [ks/s]")},
  { 1120, F("Aufnahmezeit [s]")         ,F("Recording time [s]")},
  { 1130, F("10x")                      ,0 },
  { 1131, F("20x")                      ,0 },
  { 1140, F("Schwellwert Aufnahme [db]"),F("Threshhold recording [dB]")},
  { 1141, F("Schwellwert [db]")         ,F("Threshhold[dB]")},
  { 1142, F("Datum")                    ,F("Date")},
  { 1143, F("Zeit")                     ,F("Time")},
  { 1144, F("Totzeit n. Aufnahme [s]")  ,F("Timeout after rec. [s]")},
  { 1145, F("Totzeit [s]")              ,F("Timeout [s]")},
  { 1148, F("Nachleuchtzeit [s]")       ,F("Backlight time [s]")},
  { 1150, F("Drehsinn Drehknopf")       ,F("Direction rotary knob")},
  { 1151, F("Uhrzeigersinn")            ,F("Clockwise")},
  { 1152, F("Gegenuhrzeigersinn")       ,F("Counter clockwise")},
  { 1155, F("Darstellung")              ,F("Display")},
  { 1156, F("normal")                   ,0 },
  { 1157, F("invers")                   ,0 },
  { 1160, F("Anzeige:")                 ,F("Display:")},
  { 1161, F("Linkshänder")              ,F("left handed")},
  { 1162, F("Rechtshänder")             ,F("right handed")},
  { 1165, F("Kal. Spannung [V]")        ,F("Cal. Voltage [V]")},
  { 1166, F("Abschaltspannung [V]")     ,F("Shutoff Voltage [V]")},
  { 1167, F("Verzögerung Tx USB [ms]")  ,F(")Delay Tx USB [ms]")},
  { 1170, F("Trig. Filter [kHz]")       ,0 },
  { 1171, F("Hochpass")                 ,F("High pass")},
  { 1172, F("Tiefpass")                 ,F("Low pass")},
  { 1173, F("Bandpass")                 ,F("Band pass")},
  { 1175, F("Filtertyp")                ,F("Filter type")},
  { 1176, F("Trig.Filt. [kHz]")         ,0 },
  { 1177, F("Filter [kHz]")             ,0 },
  { 1178, F("Trig.Filt.Typ")            ,F("Trig.Filt.Type")},
  { 1180, F("Startzeit")                ,F("Start Time")},
  { 1181, F("Stoppzeit")                ,F("Stop Time")},
  { 1182, F(":")                        ,0 },
  { 1183, F("-")                        ,0 },
  { 1200, F("Name deutsch")             ,F("Name")},
  { 1202, F("Name latein")              ,F("Name lat.")},
  { 1204, F("Hauptfreq. [kHz]")         ,F("Main freq. [kHz]")},
  { 1206, F("min.")                     ,F("min.")},
  { 1208, F("max.")                     ,F("max.")},
  { 1210, F("Ruflänge [ms]")            ,F("Call length [ms]")},
  { 1212, F("Rufabstand [ms]")          ,F("Call dist. [ms]")},
  { 1215, F("Charakteristik")           ,F("Characterictic")},
  { 1217, F("Vorkommen")                ,F("Ocurrence")},
  { 1220, F("Spannweite [mm]")          ,F("Wing Span [mm]")},
  { 1225, F("Gewicht [g]")              ,F("Weight [g]")},
  { 1230, F("Lebensraum")               ,F("Habitat")},
  { 1235, F("Bemerkungen")              ,F("Comments")},
  // { 1300, F("17.6")                     ,0 },
  { 1300, F("19.2")                     ,0 },
  // { 1302, F("23.4")                     ,0 },
  // { 1303, F("28.1")                     ,0 },
  { 1301, F("32")                       ,0 },
  // { 1305, F("35.3")                     ,0 },
  { 1302, F("38.4")                     ,0 },
  { 1303, F("44.1")                     ,0 },
  { 1304, F("48")                       ,0 },
  //  { 1309, F("88")                       ,0 },
  //  { 1310, F("96")                       ,0 },
  //  { 1311, F("176")                      ,0 },
  { 1305, F("192")                      ,0 },
  //  { 1306, F("234")                      ,0 },
  //  { 1314, F("281")                      ,0 },
  { 1306, F("312")                      ,0 },
  //  { 1316, F("352")                      ,0 },
  { 1307, F("384")                      ,0 },
  { 1308, F("480")                      ,0 },

  { 1325, F("Verstärkung")              ,F("Gain")},
  { 1330, F("Pre Trigger [ms]"),          0 },
  { 1331, F("27 dB"),                     0 },
  { 1332, F("36 dB"),                     0 },
  { 1333, F("45 dB"),                     0 },
  { 1334, F("54 dB"),                     0 },

  { 1338, F("letzter Ruf [kHz]")        ,F("last call [kHz]")},

  { 1340, F("°"),                         0 },
  { 1341, F("N"),                         0 },
  { 1342, F("S"),                         0 },
  { 1343, F("E"),                         0 },
  { 1344, F("W"),                         0 },
  { 1345, F("."),                         0 },
  { 1350, F("30 dB"),                     0 },
  { 1351, F("33 dB"),                     0 },
  { 1352, F("40 dB"),                     0 },
  { 1353, F("mittel"),                    F("medium")},
  { 1354, F("53 dB"),                     0 },
  { 1355, F("hoch"),                      F("high")},
  { 1359, F("Trigger"),                   0 },
  { 1360, F("Trigger Flederm."),          F("Trigger Bats")},
  { 1361, F("Pegel"),                     F("Level")},
  { 1362, F("Frequenz"),                  F("Frequency")},
  { 1363, F("Freq. + Pegel"),             F("Freq. + Level")},
  { 1364, F("Trigger Vögel"),             F("Trigger Birds")},
  { 1365, F("Status"), 0 },
  { 1370, F("min. Dauer [ms]"),           F("min. period [ms]")},
  { 1380, F("Debug Log")                , 0 },
  { 1385, F("Baud GPS")                 , 0 },
  { 1386, F("9600")                     , 0 },
  { 1387, F("115200")                   , 0 },
  { 1390, F("Disp.test")                , 0 },
  { 1391, F("Temp.test")                , 0 },
  { 1392, F("Metadaten"),                F("Meta Data")},
  { 1393, F("XML-Datei"),                F("XML File")},
  { 1394, F("Guano (wav)"),              0 },
  { 1396, F("Modus"),              F("Operation Mode")},
  { 1397, F("Fledermäuse"),              F("Bats")},
  { 1398, F("Flederm. & Vögel"),         F("Bats & Birds")},
  { 1400, F("Aus"),                      F("Off")},
  { 1401, F("Immer Flederm."),           F("Always (Bats)")},
  { 1402, F("Immer Vögel"),              F("Always (Birds)")},
  { 1403, F("Zeit alles"),               F("Time all")},
  { 1404, F("Zeit Fleder"),              F("Time Bats")},
  { 1405, F("Zeit Vögel"),               F("Time Birds")},
  { 1406, F("Dämmer.alles"),             F("Twil.all")},
  { 1407, F("Dämmer.Fleder"),            F("Twil.Bats")},
  { 1408, F("Dämmer.Vögel"),             F("Twil.Birds")},
  { 1410, F("Position manuell"),         F("Position manually")},
  { 1412, F("GPS dauernd an"),           F("GPS permanently on")},
  { 1413, F("GPS automatisch aus"),      F("GPS automatic off")},
  { 1414, F("Immer")                     ,F("Always")},
  { 1415, F("Zeitgesteuert")             ,F("Time controlled")},
  { 1416, F("Dämmerung")                 ,F("Twilight")},
  { 1420, F("Quelle Positionsangabe"),   F("Source position indication")},
  { 1421, F("Position")                  ,0},
  { 1430, F("Aus"),                      F("Off")},
  { 1431, F("Suche Satelliten"),         F("Search satelites")},
  { 1432, F("Fixed"),                    F("Fixed")},
  { 1433, F("Fixed, ausgeschaltet"),     F("Fixed, switched off")},
  { 1434, F("Suche"),                    F("Search")},
  { 1435, F("Fix")                      ,0},
  { 1436, F("Fix, Aus"),                 F("Fix, Off")},
  { 1500, F("Fledermausart"),            F("Bat Species")},
  { 1510, F("Parameter einstellen"),     F("Setup Parameters")},
  { 1600, F("Datei wirklich löschen?:"), F("Really delete file?:")},
  { 1700, F("Open Source Fledermausdetektor"),F("Open Source bat recording and detection device")},
  { 1704, F("weiter mit Taste OK...")    ,F("go on with button OK ...")},
  { 1710, F("Bedienebene"),              F("Dialog Level")},
  { 1713, F("Handgerät"),                F("Handheld")},
  { 1714, F("Kompakt"),                  F("Compact")},
  { 1720, F("Zeitzone"),                 F("Time Zone")},
  { 1730, F("Sommerzeit"),               F("Daylight Saving Time")},
  { 1740, F("Automatisch"),              F("Automatic")},
  { 2100, F("Schalte aus..."),           F("Shutting down...")},
  
  

  { 12000, F(TGE_ASC_0)           ,0},
  { 12001, F(TGE_ASC_1)           ,0},
  { 12002, F(TGE_ASC_2)           ,0},
  { 12003, F(TGE_ASC_3)           ,0},
  { 12004, F(TGE_ASC_4)           ,0},
  { 12005, F(TGE_ASC_5)           ,0},
  { 12006, F(TGE_ASC_6)           ,0},
  { 12007, F(TGE_ASC_7)           ,0},
  { 12008, F(TGE_ASC_8)           ,0},
  { 12010, F(TGE_DOUBLE)          ,0},
  { 0xFFFF   , F("")           ,F("")},
};

void printSize()
{
  Serial.printf("Size texts: %i" ,sizeof(Texts));
}